FROM node:7.4 as build

# Node deps
WORKDIR /app
COPY ./package.json /app/package.json
RUN npm install
COPY ./  /app
RUN npm run lint
RUN npm run build

FROM nginx
RUN rm -rf /etc/nginx/sites-enabled/*
COPY ./nginx/ /etc/nginx/conf.d/
COPY --from=build /app/dist /app/dist
